-- MySQL Script generated by MySQL Workbench
-- Sun Apr 17 23:27:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PDD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PDD` ;

-- -----------------------------------------------------
-- Schema PDD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PDD` DEFAULT CHARACTER SET utf8 ;
USE `PDD` ;

-- -----------------------------------------------------
-- Table `PDD`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PDD`.`users` ;

CREATE TABLE IF NOT EXISTS `PDD`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `access` INT(11) NOT NULL,
  PRIMARY KEY (`idusers`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PDD`.`driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PDD`.`driver` ;

CREATE TABLE IF NOT EXISTS `PDD`.`driver` (
  `name` VARCHAR(45) NOT NULL,
  `passport` VARCHAR(9) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NULL,
  `birthday` DATE NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `passport_UNIQUE` (`passport` ASC) VISIBLE,
  PRIMARY KEY (`passport`),
  INDEX `login_idx` (`login` ASC) VISIBLE,
  CONSTRAINT `login`
    FOREIGN KEY (`login`)
    REFERENCES `PDD`.`users` (`login`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PDD`.`auto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PDD`.`auto` ;

CREATE TABLE IF NOT EXISTS `PDD`.`auto` (
  `numberauto` VARCHAR(8) NOT NULL,
  `brand` VARCHAR(100) NOT NULL,
  `passport` VARCHAR(9) NOT NULL,
  UNIQUE INDEX `numberauto_UNIQUE` (`numberauto` ASC) VISIBLE,
  PRIMARY KEY (`numberauto`),
  INDEX `passport_idx` (`passport` ASC) VISIBLE,
  CONSTRAINT `passport`
    FOREIGN KEY (`passport`)
    REFERENCES `PDD`.`driver` (`passport`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PDD`.`typeviolations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PDD`.`typeviolations` ;

CREATE TABLE IF NOT EXISTS `PDD`.`typeviolations` (
  `article` VARCHAR(45) NOT NULL,
  `nameviolations` VARCHAR(255) NOT NULL,
  `base` FLOAT NOT NULL,
  UNIQUE INDEX `article_UNIQUE` (`article` ASC) VISIBLE,
  PRIMARY KEY (`article`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PDD`.`violations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PDD`.`violations` ;

CREATE TABLE IF NOT EXISTS `PDD`.`violations` (
  `idviolations` INT NOT NULL AUTO_INCREMENT,
  `arcitle` VARCHAR(45) NOT NULL,
  `violationdatetime` DATETIME NOT NULL,
  `fine` FLOAT NOT NULL,
  `numberauto` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idviolations`),
  INDEX `article_idx` (`arcitle` ASC) VISIBLE,
  INDEX `numberauto_idx` (`numberauto` ASC) VISIBLE,
  CONSTRAINT `article`
    FOREIGN KEY (`arcitle`)
    REFERENCES `PDD`.`typeviolations` (`article`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `numberauto`
    FOREIGN KEY (`numberauto`)
    REFERENCES `PDD`.`auto` (`numberauto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PDD`.`pay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PDD`.`pay` ;

CREATE TABLE IF NOT EXISTS `PDD`.`pay` (
  `idpay` INT NOT NULL AUTO_INCREMENT,
  `idviolations` INT NOT NULL,
  `paymentcard` INT(16) NOT NULL,
  `expirationdate` INT(4) NOT NULL,
  `sum` FLOAT NOT NULL,
  PRIMARY KEY (`idpay`),
  UNIQUE INDEX `paymentcard_UNIQUE` (`paymentcard` ASC) VISIBLE,
  INDEX `idviolations_idx` (`idviolations` ASC) VISIBLE,
  CONSTRAINT `idviolations`
    FOREIGN KEY (`idviolations`)
    REFERENCES `PDD`.`violations` (`idviolations`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
